// Generated by gencpp from file game_engine/ShootAndTurbo.msg
// DO NOT EDIT!


#ifndef GAME_ENGINE_MESSAGE_SHOOTANDTURBO_H
#define GAME_ENGINE_MESSAGE_SHOOTANDTURBO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace game_engine
{
template <class ContainerAllocator>
struct ShootAndTurbo_
{
  typedef ShootAndTurbo_<ContainerAllocator> Type;

  ShootAndTurbo_()
    : shoot(false)
    , turbo(false)  {
    }
  ShootAndTurbo_(const ContainerAllocator& _alloc)
    : shoot(false)
    , turbo(false)  {
  (void)_alloc;
    }



   typedef uint8_t _shoot_type;
  _shoot_type shoot;

   typedef uint8_t _turbo_type;
  _turbo_type turbo;





  typedef boost::shared_ptr< ::game_engine::ShootAndTurbo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::game_engine::ShootAndTurbo_<ContainerAllocator> const> ConstPtr;

}; // struct ShootAndTurbo_

typedef ::game_engine::ShootAndTurbo_<std::allocator<void> > ShootAndTurbo;

typedef boost::shared_ptr< ::game_engine::ShootAndTurbo > ShootAndTurboPtr;
typedef boost::shared_ptr< ::game_engine::ShootAndTurbo const> ShootAndTurboConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::game_engine::ShootAndTurbo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::game_engine::ShootAndTurbo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace game_engine

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'game_engine': ['/home/sergio/teste420/src/game_engine/msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_engine::ShootAndTurbo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::game_engine::ShootAndTurbo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_engine::ShootAndTurbo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6396303e74b55d0dd0145a9a5dfed363";
  }

  static const char* value(const ::game_engine::ShootAndTurbo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6396303e74b55d0dULL;
  static const uint64_t static_value2 = 0xd0145a9a5dfed363ULL;
};

template<class ContainerAllocator>
struct DataType< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "game_engine/ShootAndTurbo";
  }

  static const char* value(const ::game_engine::ShootAndTurbo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool shoot\n\
bool turbo\n\
";
  }

  static const char* value(const ::game_engine::ShootAndTurbo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shoot);
      stream.next(m.turbo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootAndTurbo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::game_engine::ShootAndTurbo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::game_engine::ShootAndTurbo_<ContainerAllocator>& v)
  {
    s << indent << "shoot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shoot);
    s << indent << "turbo: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turbo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAME_ENGINE_MESSAGE_SHOOTANDTURBO_H
