# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from game_engine/WallInfoArray.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import game_engine.msg

class WallInfoArray(genpy.Message):
  _md5sum = "00bbbcfc52895902500308e3cbae4262"
  _type = "game_engine/WallInfoArray"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """WallInfo[] wall

================================================================================
MSG: game_engine/WallInfo
int8 id
int8 cluster
int16 x1
int16 x2
int16 y1
int16 y2
float64 xc
float64 yc
int8 life
bool vertical
"""
  __slots__ = ['wall']
  _slot_types = ['game_engine/WallInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wall

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WallInfoArray, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.wall is None:
        self.wall = []
    else:
      self.wall = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.wall)
      buff.write(_struct_I.pack(length))
      for val1 in self.wall:
        _x = val1
        buff.write(_get_struct_2b4h2dbB().pack(_x.id, _x.cluster, _x.x1, _x.x2, _x.y1, _x.y2, _x.xc, _x.yc, _x.life, _x.vertical))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.wall is None:
        self.wall = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.wall = []
      for i in range(0, length):
        val1 = game_engine.msg.WallInfo()
        _x = val1
        start = end
        end += 28
        (_x.id, _x.cluster, _x.x1, _x.x2, _x.y1, _x.y2, _x.xc, _x.yc, _x.life, _x.vertical,) = _get_struct_2b4h2dbB().unpack(str[start:end])
        val1.vertical = bool(val1.vertical)
        self.wall.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.wall)
      buff.write(_struct_I.pack(length))
      for val1 in self.wall:
        _x = val1
        buff.write(_get_struct_2b4h2dbB().pack(_x.id, _x.cluster, _x.x1, _x.x2, _x.y1, _x.y2, _x.xc, _x.yc, _x.life, _x.vertical))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.wall is None:
        self.wall = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.wall = []
      for i in range(0, length):
        val1 = game_engine.msg.WallInfo()
        _x = val1
        start = end
        end += 28
        (_x.id, _x.cluster, _x.x1, _x.x2, _x.y1, _x.y2, _x.xc, _x.yc, _x.life, _x.vertical,) = _get_struct_2b4h2dbB().unpack(str[start:end])
        val1.vertical = bool(val1.vertical)
        self.wall.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b4h2dbB = None
def _get_struct_2b4h2dbB():
    global _struct_2b4h2dbB
    if _struct_2b4h2dbB is None:
        _struct_2b4h2dbB = struct.Struct("<2b4h2dbB")
    return _struct_2b4h2dbB
