(cl:in-package game_engine-msg)
(cl:export '(TEAMID-VAL
          TEAMID
          TAGID-VAL
          TAGID
          X-VAL
          X
          Y-VAL
          Y
          HEIGHT-VAL
          HEIGHT
          ANGLE-VAL
          ANGLE
          ADDR0-VAL
          ADDR0
          ADDR1-VAL
          ADDR1
          VEL1-VAL
          VEL1
          VEL2-VAL
          VEL2
          PREVIOUS_VEL-VAL
          PREVIOUS_VEL
          COLLISIONFLAG-VAL
          COLLISIONFLAG
          THREADISRUNNING-VAL
          THREADISRUNNING
          COLLISIONSTATEVAR-VAL
          COLLISIONSTATEVAR
          AUTONOMOUS_DRIVE-VAL
          AUTONOMOUS_DRIVE
          IMMOBILIZED-VAL
          IMMOBILIZED
          DAMAGE-VAL
          DAMAGE
          KILLS-VAL
          KILLS
          CLASSIFICATION-VAL
          CLASSIFICATION
))